### ISSUE TITLE
Описание аннотаций

### ISSUE THREAD

**Issue by Nivanchenko** [Nivanchenko/autumn-killjoy#1]
- [X] Желудь - Компонент
- [X] Компанейский желудь -  Прототип 
- [x] Верховный -  Приоритетный
- [x] Дуб - Конфигурация
- [x] Завязь - ФабричныйМетод
- [x] Заготовка -  ИнициализаторПриложения
- [x] Напильник - ОбработчикКомпонента
- [x] Прозвище - Квалификатор
- [x] Рогатка - ЗапускательПриложения
- [x] Деталька - ЗначениеНастройки
- [x] Блестяшка - ПроизвольныйПараметр
- [x] Пластилин - Внедряемое

Все обсуждается, рад любым предложениям.

**Comment by nixel2007** [comment]
Верховный - Приоритетный/Главный (primary).
Деталька - ЗначениеНастройки (value).
Пластилин - Автосвязываемое, Внедряемое (autowired)
Блестяшка - ПроизвольныйПараметр, Произвольное

**Comment by nixel2007** [comment]
Дуб - Конфигурация (configuration)
Прозвище - Квалификатор (qualifier)

**Comment by Nivanchenko** [comment]
Все аннотации готовы. только детальки, блестяшки и пластилин не работают на конструкторе, там пока в тестах типовые аннотации.
